stages:
    - check

.php_rules: &php_rules
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
          changes:
              - "docker/**/*"
              - "tests/**/*"
              - "translations/**/*"
              - "templates/**/*"
              - "config/**/*"
              - "src/**/*"
              - "*.json"
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
              - "docker/**/*"
              - "tests/**/*"
              - "translations/**/*"
              - "templates/**/*"
              - "config/**/*"
              - "src/**/*"
              - "*.json"

.node_rules: &node_rules
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
          changes:
              - "docker/**/*"
              - "tests/**/*"
              - "*.json"
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
              - "docker/**/*"
              - "tests/**/*"
              - "*.json"

php:
    <<: *php_rules
    stage: check
    image: php:8.5-cli
    services:
        - name: mariadb
          alias: mariadb
    variables:
        MARIADB_ROOT_PASSWORD: root
        MARIADB_DATABASE: db_symfony_test
        DATABASE_URL: mysql://root:root@mariadb:3306/db_symfony_test?serverVersion=12.3.1-MariaDB&charset=utf8mb4
    before_script:
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - curl -sS https://get.symfony.com/cli/installer | bash -s -- --install-dir=/usr/local/bin
        - composer install --no-interaction --prefer-dist
    cache:
        key:
            files:
                - composer.lock
        paths:
            - vendor/
    script:
        - symfony check:requirements
        - composer run lint
        - composer run test

node:
    <<: *node_rules
    stage: check
    image: node:26
    before_script:
        - npm install -g pnpm@10.6.5
        - pnpm install --frozen-lockfile
    cache:
        key:
            files:
                - pnpm-lock.yaml
        paths:
            - node_modules/
    script:
        - pnpm run build
        - pnpm run lint
        - pnpm run test
