stages:
    - check

workflow:
    rules:
        -   if: $CI_COMMIT_BRANCH == "main"
        -   if: $CI_PIPELINE_SOURCE == "merge_request_event"

php:
    stage: check
    image: php:8.4-cli
    services:
        - name: mariadb:12.3.1
          alias: mariadb
    variables:
        MARIADB_ROOT_PASSWORD: root
        MARIADB_DATABASE: db_symfony_test
        DATABASE_URL: mysql://root:root@mariadb:3306/db_symfony_test?serverVersion=12.3.1-MariaDB&charset=utf8mb4
    before_script:
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - composer install --no-interaction --prefer-dist
    cache:
        key:
            files:
                - composer.lock
        paths:
            - vendor/
    script:
        - composer run lint
        - composer run format
        - composer run test

node:
    stage: check
    image: node:25.8.2
    before_script:
        - npm install -g pnpm@10.6.5
        - pnpm install --frozen-lockfile
    cache:
        key:
            files:
                - pnpm-lock.yaml
        paths:
            - node_modules/
    script:
        - pnpm run lint
        - pnpm run format
        - pnpm run test
