services:
    php:
        build:
            dockerfile: Dockerfile
            target: php
        volumes:
            - ./:/var/www/html

    node:
        build:
            dockerfile: Dockerfile
            target: node
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www/html

    #
    # Development
    #

    db:
        image: mariadb
        environment:
            MARIADB_DATABASE: db_symfony
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - db:/var/lib/mysql
        ports:
            - "3306:3306"

    caddy:
        image: caddy
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        ports:
            - "8443:443"
            - "8443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - .:/var/www/html
        depends_on:
            - php

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_ARBITRARY=1
        depends_on:
            - db

    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"

volumes:
    db:
    caddy_data:
    caddy_config:
