services:
    db:
        image: mariadb:12.3.1-rc
        environment:
            MARIADB_DATABASE: db_symfony
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3306:3306

    php:
        build:
            dockerfile: Dockerfile
            target: php
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db

    caddy:
        image: caddy:2.11
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        ports:
            - "8443:443"
            - "8443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - .:/var/www/html
        depends_on:
            - php

    node:
        build:
            dockerfile: Dockerfile
            target: node
        tty: true
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php

    #
    # Tools
    #

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_ARBITRARY=1
        depends_on:
            - db

    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"
        depends_on:
            - php

volumes:
    db:
    caddy_data:
    caddy_config:
