name: CI

on:
    push:
        branches:
            - main
        paths:
            - "docker/**"
            - "tests/**"
            - "translations/**"
            - "templates/**"
            - "config/**"
            - "src/**"
            - "*.json"
            - "vite.config.ts"
    pull_request:
        branches:
            - main

jobs:
    php:
        name: PHP
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb
                env:
                    MARIADB_ROOT_PASSWORD: root
                    MARIADB_DATABASE: db_symfony_test
                ports:
                    - 3306:3306
                options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=5
        steps:
            - uses: actions/checkout@v5

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.4"
                  tools: composer

            - name: Install Symfony CLI
              run: curl -sS https://get.symfony.com/cli/installer | bash -s -- --install-dir=/usr/local/bin

            - name: Install
              run: composer install --no-interaction --prefer-dist

            - name: Requirements
              run: symfony check:requirements

            - name: Lint
              run: composer run lint

            - name: Test
              run: composer run test
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/db_symfony_test?serverVersion=12.3.1-MariaDB&charset=utf8mb4
